name: Build and Push payment service
run-name: build-payments

on:
  push:
    branches: ["main", "payments"]
    paths:
      - '**.js'
      - '**.yaml'
    tags:
      - "*"
  pull_request:
    branches: ["main"]
    paths:
      - '**.js'
      - '**.yaml'
    types:
      - closed
  workflow_dispatch:

env:
  PAYMENT_IMAGE: payment

jobs:
  build-payment:
    name: build and push payment image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/payments-svc
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./backend/payments-svc/
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.PAYMENT_IMAGE}}
